### PR TITLE
refactor: routes refactoring

### PR DESCRIPTION
**Pull request by mtoohey31**
This PR contains quite a few changes, mainly related to extracting commonly used methods and improving error handling. Unfortunately, this code is currently quite difficult to test because it requires a database that the backend can connect to and the Senso credentials, so I don't have any good suggestions for testing it right now...

### CODE REVIEW

**Comment by mtoohey31** [comment]
There's still two remaining `TODO` comments in these files, the first is related to checking for null values in `ParseCarUseCase` and `ParseCarBuyerUseCase`, so we just have to make sure we remove the comment in these files after we fix that.

The second one is related to abstracting JSON stuff more. @gnguralnick would you be able to take a look at that? The comment in question is the one on line 71 of `Loan.java`.

**Comment by gnguralnick** [comment]
the TODO there was due to the fact that Loan.java is directly calling JsonObjectBuilder and JsonPackager rather than using the interfaces like the use cases do. I'm not sure though if there's any way to do this without just directly calling those, unless we put the packager or builder as parameters or instance attributes in Loan.java, which might just be unnecessarily complicated.

**Comment by mtoohey31** [comment]
Ok, yeah for now I think we can leave it, plus that's really more of a refactor that needs to happen in that other package, so it shouldn't really be part of this PR anyways. I might leave the comment just so we know about it though, we can come back to it when we get to formatting those.

**Review by Mogtaba-Alim — COMMENTED** [review]
A suggestion I have would be to convert some of these try and catch blocks to refactored methods for better readability. What do you think?

**Review by Mogtaba-Alim — APPROVED** [review]
Seems Fine

**Pull request merged**
